# Project: myC
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o myScan.o $(RES)
LINKOBJ  = main.o myScan.o $(RES)
LIBS =  -L"E:/programfile/Dev/Dev-Cpp/lib"  
INCS =  -I"E:/programfile/Dev/Dev-Cpp/include" 
CXXINCS =  -I"E:/programfile/Dev/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"E:/programfile/Dev/Dev-Cpp/include/c++/3.4.2/backward"  -I"E:/programfile/Dev/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"E:/programfile/Dev/Dev-Cpp/include/c++/3.4.2"  -I"E:/programfile/Dev/Dev-Cpp/include" 
BIN  = myC.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before myC.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "myC.exe" $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

myScan.o: myScan.c
	$(CC) -c myScan.c -o myScan.o $(CFLAGS)
